.github/workflows/release-beta.yml, .github/workflows/release-prod.yml
=> feat: #18 adds beta release workflow

.github/workflows/release-beta.yml, .github/workflows/release-prerelease.yml
=> feat: #18 update beta release workflow

src/storybook/changelog.stories.mdx
=> feat: #18 final tidy

src/storybook/changelog.stories.mdx
=> docs: added prettier update to change log

.storybook/main.mjs, package.json, src/components/form-layout/form-layout.mdx, src/components/grid/grid.mdx, src/components/icon/icon.mdx, src/components/page-header/__tests__/__snapshots__/page-header.test.tsx.snap, src/components/placeholder-image/placeholder-image.mdx, src/components/tabs/__tests__/__snapshots__/tabs.test.tsx.snap, src/components/tabs/tabs.tsx, src/hooks/use-media-query/media.mdx, src/storybook/render-html-markup.tsx, src/styles/utilities.stories.mdx, yarn.lock
=> feat: #22 gitHub mdx table replacements

src/components/button/__styles__/index.ts, src/components/card/card-components.tsx, src/components/nav/__styles__/index.ts, src/components/nav/nav-responsive.tsx, src/components/progress-bar/__styles__/index.ts, src/icons/icons-legacy.ts, src/styles/globals.ts, src/styles/intent.ts
=> feat: added decorated deprecate methods

src/components/persistent-notification/__styles__/index.ts, src/storybook/changelog.mdx
=> fix: added z-index auto value to prevent z-index over menu component

src/components/modal/__styles__/index.ts, src/storybook/changelog.mdx
=> fix: #29 #67 fix modal height issue

src/components/form-layout/form-layout.stories.tsx, src/components/select/__styles__/index.ts, src/storybook/changelog.mdx
=> fix: #88 select incorrect height

src/components/drawer/drawer.mdx, src/components/drawer/drawer.stories.tsx, src/components/form-layout/__styles__/index.ts, src/components/form-layout/__tests__/__snapshots__/form-layout.test.tsx.snap, src/components/form-layout/__tests__/form-layout.test.tsx, src/components/form-layout/form-layout.tsx, src/components/input/__styles__/index.ts, src/components/select/__styles__/index.ts, src/storybook/changelog.mdx
=> fix: #64 fixes issue with forms in Drawer components

.github/workflows/release-beta.yml, .github/workflows/release-dev.yml, .github/workflows/release-prerelease.yml, .github/workflows/release-prod.yml, package.json, scripts/cdk/cdk-stack.ts
=> feat: #90 move v4 to lts

src/hooks/use-media-query/index.tsx, src/hooks/use-nav-state/__tests__/index.test.tsx, src/hooks/use-nav-state/index.tsx, src/hooks/use-snack/__tests__/index.test.tsx, src/hooks/use-snack/index.tsx, src/styles/theme-provider.tsx, src/types/core.ts
=> fix: #59 polyfill props with children

src/components/breadcrumb/breadcrumb.mdx, src/components/file-input/file-input.mdx, src/components/input-group/input-group.mdx, src/components/input/input.mdx, src/storybook/changelog.mdx
=> fix: #109 input types incorrect

src/components/breadcrumb/breadcrumb.mdx, src/components/file-input/file-input.mdx, src/components/input-group/input-group.mdx, src/components/input/input.mdx, src/storybook/changelog.mdx
=> fix: #109 input rendering issue

src/components/file-input/__tests__/__snapshots__/file-input.test.tsx.snap, src/components/nav/__tests__/__snapshots__/nav-responsive.test.tsx.snap, src/styles/spacing.ts
=> fix: #118 misspelled spacing utils

.github/workflows/test-pr.yml, jest.config.js
=> feat: add codacy

src/components/nav/__styles__/index.ts, src/storybook/changelog.mdx
=> fix: nav menu broken

src/components/button-group/__tests__/__snapshots__/button-group.test.tsx.snap, src/components/button-group/button-group.stories.tsx, src/components/button/__tests__/__snapshots__/button.test.tsx.snap, src/components/button/__tests__/button.test.tsx, src/components/button/button.stories.tsx, src/components/button/button.tsx, src/components/dialog/dialog.stories.tsx, src/components/drawer/drawer.stories.tsx, src/components/file-input/__styles__/index.ts, src/components/file-input/__tests__/__snapshots__/file-input.test.tsx.snap, src/components/file-input/file-input.stories.tsx, src/components/form-layout/form-layout.stories.tsx, src/components/mobile-controls/__tests__/__snapshots__/mobile-controls.test.tsx.snap, src/components/mobile-controls/mobile-controls.tsx, src/components/modal/modal.stories.tsx, src/components/page-header/__tests__/__snapshots__/page-header.test.tsx.snap, src/components/page-header/__tests__/page-header.test.tsx, src/components/page-header/page-header.stories.tsx, src/components/page-header/page-header.tsx, src/components/snack/use-snack-hook.story-component.tsx, src/components/steps/steps.stories.tsx, src/components/table/table.stories.tsx, src/hooks/use-modal/modal.stories.tsx, src/patterns/layout.stories.tsx, src/styles/theming.mdx, src/styles/theming.stories.tsx
- Updated existing button usage throughout elements to replace new props.
=> refactor: #140 part2 v5 component refactor buttons

src/storybook/changelog.mdx
fixes: # updated change log to represent correct version
=> chore: #140 Update change log to represent correct version

src/components/nav-item/__tests__/__snapshots__/nav-item.test.tsx.snap, src/components/nav-item/__tests__/nav-item.test.tsx, src/components/nav-item/index.ts, src/components/nav-item/nav-item.mdx, src/components/nav-item/nav-item.stories.tsx, src/components/nav-item/nav-item.tsx, src/components/nav-item/styles.ts, src/components/nav/__styles__/index.ts
this is small part of the app-bar component, which will be used in the top bar navigation.
***app bar (parent)***
***this ticket***
=> feat: #195 new app-bar (nav item)

src/components/avatar-button/__tests__/__snapshots__/avatar-button.test.tsx.snap, src/components/avatar-button/__tests__/avatar-button.test.tsx, src/components/avatar-button/avatar-button.mdx, src/components/avatar-button/avatar-button.stories.tsx, src/components/avatar-button/avatar-button.tsx, src/components/avatar-button/index.ts, src/components/avatar-button/styles.ts, src/components/nav-item/nav-item.mdx
this is small part of the app-bar component, which will be used in the top bar navigation.
***app bar (parent)***
***this ticket***
https://github.com/user-attachments/assets/712dfbeb-31d1-4aae-be79-f68564dae636
=> feat: #195 new app-bar (avatar button)

src/components/button/button.stories.tsx, src/components/button/button.tsx, src/components/button/styles.ts
fixes: Housekeeping issues resolved.
=> refactor: #226 v5 Button Component housekeeping updates

src/components/skeleton/__tests__/__snapshots__/skeleton.test.tsx.snap, src/components/skeleton/__tests__/skeleton.test.tsx, src/components/skeleton/index.ts, src/components/skeleton/skeleton.mdx, src/components/skeleton/skeleton.stories.tsx, src/components/skeleton/skeleton.tsx, src/components/skeleton/styles.ts, src/index.ts
- Added new component Skeleton
- Only implemented blink(pulse) animation. We can amend new animations with props if DS requires changes.
- It can be used within actual components and can be utilise in `<Suspense />`
=> feat: #228 New component skeleton

src/components/avatar/styles.ts, src/components/dialog/styles.ts, src/components/menu/styles.ts, src/components/nav-dropdown-button/styles.ts, src/components/nav-item/styles.ts, src/components/nav-search-button/styles.ts, src/components/table/table-toolbar/styles.ts, src/tokens/payprop/tokens.css, src/tokens/payprop/tokens.ts, src/tokens/reapit/tokens.css, src/tokens/reapit/tokens.ts, src/tokens/tokens.json
**fixes:**
- Updated token files to read correct font-weight values same as figma
- Updated respective files using hard-coded font-weight values.
=> chore: #263 v5 Fix token file for font-weight variable values

src/components/badge/styles.ts
=> fix: 289 added badge label container

src/components/tooltip/__tests__/__snapshots__/tooltip.test.tsx.snap, src/components/tooltip/__tests__/use-tooltip.test.tsx, src/components/tooltip/styles.ts, src/components/tooltip/tooltip.stories.tsx, src/components/tooltip/use-tooltip.ts
fixes: Added animation as the issue was raised due to race condition of rendering the tooltip to DOM v/s the calculation done to get the position of the trigger to place the tooltip.
=> fix: #291 Fixed issue with the placement of the tooltip

src/components/side-bar/__test__/__snapshots__/side-bar.test.tsx.snap, src/components/side-bar/__test__/side-bar.test.tsx, src/components/side-bar/index.ts, src/components/side-bar/side-bar.mdx, src/components/side-bar/side-bar.stories.tsx, src/components/side-bar/side-bar.tsx, src/components/side-bar/styles.ts, src/storybook/figma/index.tsx
In order to create a new SideBar for the v5 release, this PR, as part of #154, initended to initiate the base component for SideBar.
fixes: #
=> feat: #154 v5 new SideBar (base)

src/components/mobile-nav-item/styles.ts
fixes: #
resolve the feedback that has been given by design team https://github.com/reapit/elements/issues/224#issuecomment-2620769647
=> fix: #206 mobile nav item design feedback

src/components/bottom-bar-item/styles.ts, src/components/bottom-bar/__tests__/__snapshots__/bottom-bar.test.tsx.snap, src/components/bottom-bar/bottom-bar.atoms.tsx, src/components/bottom-bar/styles.ts
fixes: #
part of #224 
**Context:**
Following the unmatched style between the design and actual component feedback https://github.com/reapit/elements/issues/224#issuecomment-2620769647 we also need to little amendment for this one
=> fix: #224 bottom bar item design feedback

src/storybook/changelog.mdx
A changelog for the new elements was added, and those were refactored for v5.
=> chore: #340 Beta release change log update

package.json, src/components/badge/styles.ts, src/storybook/changelog.mdx
- Fix the issue with CSS properties declaration within the Badge component
- Updated export for CSS to persist the import value for the existing beta users
fixes: #346
=> fix: #346 Fix issue with beta 18 release

package.json, src/storybook/changelog.mdx, vite.config.ts, yarn.lock
fixes: #348 Updated the vite config to export types so that current consumers who import types avoid any import errors.
=> fix: #348 Updated vite config to add the export types to production build

package.json
fixes: #348 Update package version
=> fix: #348 Update package version to 20

package.json, src/storybook/changelog.mdx
fixes: #348 Updated package version for resolving the publish
=> fix: #348 update package version to 21 due to failed publish for version 20

package.json, src/storybook/changelog.mdx, vite.config.ts
fixes: #348 Fix issue with imports path in the build `.d.ts` files.
=> fix: #348 Fix issue with imports path in the build  files.

src/components/mobile-nav-item/styles.ts
fixes: #369 
- add missing css variable based on QA feedback
=> fix: #369 (mobile-nav-item) add missing css variables

src/styles/globals.ts
=> fix: corrected ---util-rems-4 var name

package.json, src/storybook/changelog.mdx
fixes: #403 Release Beta 5.0.0-beta.23
=> chore: #403 Prepare v5 beta release 5.0.0-beta.23

package.json, src/index.ts, src/storybook/changelog.mdx
=> fix: #405 Fix the export path for the v5 Nav-item

package.json, src/storybook/changelog.mdx
fixes: #432 
- Bump up package manifest file for beta release version 5.0.0-beta.27
- Updated change log
=> chore: #432 Prepare release for Beta-5.0.0-beta.27

src/components/badge/styles.ts, src/components/icon/__styles__/index.ts
CM ticket: [CM-131](https://agentbox.atlassian.net/browse/CM-131)
**Detail as per issue below:**
- Updated badge component with updated DS token variables
- Added the align-item center on the el-icon class
=> feat: #435 Updated badge component with updated DS token variables

src/components/badge/styles.ts
**Jira Ticket**
[CM-131](https://agentbox.atlassian.net/browse/CM-131)
fixes: updated the missing DS tokens
=> fix: #440 Updated badge component with missing ds token variables

src/components/nav-search-button/styles.ts, src/components/top-bar/top-bar.stories.tsx
#438 was merged but some commits hadn't been pushed from my local branch 🤦 This adds in the necessary review changes.
=> fix: add missing commit from #438

package.json, src/storybook/changelog.mdx
=> chore: #472 bump to v5.0.0-beta.30 and update changelog

src/storybook/changelog.mdx
Changelog wasn't updated by #501. This PR adds the necessary entry.
=> chore: update Storybook changelog re preprocessing of token files

src/components/avatar/styles.ts, src/index.ts
- The `TopBar` refactor work was merged before review (due to hackathon). Review feedback is now in.
- The recently added `SupplementaryInfo` wasn't properly exported from the root barrel file
- Actions PR feedback for `TopBar` refactor work
- Exports `SupplementaryInfo`
=> chore: scout Avatar sizing and SupplementaryInfo export

src/storybook/changelog.mdx
=> chore: update changelog with release date

package.json, src/storybook/changelog.mdx
=> chore: bump package version

src/storybook/changelog.mdx, src/tokens/Semantics.PayProp.tokens.json, src/tokens/Semantics.Reapit.tokens.json, src/tokens/dist/payprop.css, src/tokens/dist/reapit.css
=> chore: update design tokens

src/storybook/changelog.mdx
=> chore: add date for beta.32 release in changelog

src/index.ts, src/storybook/changelog.mdx
=> chore: export app switcher

src/components/steps/__styles__/index.ts, src/styles/globals.ts
Not sure how these got through #550 🤔
=> chore: fix css lint issues

src/core/checkbox-group/styles.ts, src/core/empty-data/styles.ts, src/core/label-text/styles.ts, src/core/mobile-nav-item/styles.ts, src/core/pagination/styles.ts, src/core/side-bar/menu-item/styles.ts, src/core/table/table-text/styles.ts, src/core/table/table-toolbar/styles.ts, src/core/top-bar/nav-search-button/styles.ts, src/storybook/changelog.mdx
=> chore: use `font` helper in all core components

src/core/folder-tabs/tab/tab.stories.tsx, src/core/folder-tabs/tab/tab.tsx, src/storybook/changelog.mdx
=> fix: `FolderTabs` documentation links
