- .github/new-issue-assignment.yml
- adds a new workflow that will automatically assign any new issues to the Internal Platform Backlog project and label them with the refinement label
> chore: add platform project issue assignment workflow

- src/components/textarea/__tests__/__snapshots__/textarea.test.tsx.snap
- src/components/textarea/__tests__/textarea.test.tsx
- src/components/textarea/__tests__/use-resize-textarea-effect.test.tsx
- src/components/textarea/__tests__/use-resize-textarea-onchange.test.tsx
- src/components/textarea/is-css-content-fieldsizing-supported.ts
- src/components/textarea/styles.ts
- src/components/textarea/sync-textarea-height.ts
- src/components/textarea/textarea.atoms.tsx
- src/components/textarea/textarea.stories.tsx
- src/components/textarea/use-resize-textarea-effect.ts
- src/components/textarea/use-resize-textarea-onchange.ts
- src/helpers/mergeRefs.ts
- src/storybook/changelog.mdx
- #136 describes updates needed for the TextArea component to align with the Design System;
- The key breaking change is that the TextArea can no longer be manually resized; rather, it should grow/shrink based on the amount of content entered.
- I am leveraging an experimental CSS property, [field-sizing](https://developer.mozilla.org/en-US/docs/Web/CSS/field-sizing) to achieve the resizing behaviour for CSS-only and React consumers on Chrome and Edge browsers, with a fallback to a JS-based resizing solution for React-only consumers on other browsers.
- This work is split across two PRs:
- #150 
- 👉 **Part 2: Add JS fallback for resizing**
Resolves #136 
- Adds a JS-based fallback for resizing the text area that we use when the [field-sizing](https://developer.mozilla.org/en-US/docs/Web/CS …
> refactor: #136 TextArea - Add JS fallback for resizing

- src/styles/globals.ts
Fixes #184 
Changes from using an `@import url(...)` statement within the global `css` block to using a bare ES module import so that the token.css file's content is correclty included in the Rollup build. See #184 for more details.
**Before:**
**After:**
> fix: #184 index.css correctly includes design tokens

- src/components/menu/__tests__/menu-popover.test.tsx
- src/components/menu/menu-context.tsx
- src/components/menu/menu-popover.tsx
- src/components/menu/menu.atoms.tsx
- src/components/menu/styles.ts
- src/hooks/use-menu/__tests__/index.test.tsx
- src/hooks/use-menu/index.tsx
continuing the sequence of pr for menu that have been discussed https://github.com/reapit/elements/issues/163, this is the 4th pr which only focus on keyboard interaction based on https://www.w3.org/WAI/ARIA/apg/patterns/menubar, here I provide basic keyboard interaction only for menu and menu items related component.
an exception here: since the menu doesn't have sub-menu, the keyboard interaction only focus to the menu-button and menu items
- new menu keyboard interaction
> feat: #163 new menu (keyboard interaction)

- src/components/nav-icon-item/__tests__/__snapshots__/nav-icon-item.test.tsx.snap
- src/components/nav-icon-item/__tests__/nav-icon-item.test.tsx
- src/components/nav-icon-item/index.ts
- src/components/nav-icon-item/nav-icon-item.mdx
- src/components/nav-icon-item/nav-icon-item.stories.tsx
- src/components/nav-icon-item/nav-icon-item.tsx
- src/components/nav-icon-item/styles.ts
Following on the discussion on #164 , we've made an agreement on separating the `NavIconItem` and `BottomBarItem` as a different component
**Context:**
The `NavIconItem` component is a small part of the `AppBar` component. It appears as a secondary navigation item on the AppBar when the screen width exceeds 1440 pixels (see the placement on the image attachment)
This PR initiates the construction of the `NavIconItem` component. It prioritizes the implementation of fundamental states (default, focus, hover, and active) while deferring the addition of supplementary elements such as tooltips and indicators. Further deliberation with the design team is required to finalize these details
**View Preview:** …
> feat: #164 - add nav icon item component

- src/components/nav-icon-item/__tests__/__snapshots__/nav-icon-item.test.tsx.snap
- src/components/nav-icon-item/__tests__/nav-icon-item.test.tsx
- src/components/nav-icon-item/nav-icon-item.mdx
- src/components/nav-icon-item/nav-icon-item.stories.tsx
- src/components/nav-icon-item/nav-icon-item.tsx
- src/components/nav-icon-item/styles.ts
part of #164 
Based on the [ticket discussion](https://github.com/reapit/elements/issues/164#issuecomment-2463641777), we're slightly agree to have the simple "red dot" within the `NavIconItem` component
Design Spec https://www.figma.com/design/XJ6qcAV8gHscsUodqJMNEF/Reapit-Elements-production-ready-components?node-id=18-6156&node-type=instance&m=dev
> feat: #164 - add simple red dot badge to NavIconItem

- src/components/bottom-bar-item/__tests__/__snapshots__/bottom-bar-item.test.tsx.snap
- src/components/bottom-bar-item/__tests__/bottom-bar-item.test.tsx
- src/components/bottom-bar-item/bottom-bar-item.mdx
- src/components/bottom-bar-item/bottom-bar-item.stories.tsx
- src/components/bottom-bar-item/bottom-bar-item.tsx
- src/components/bottom-bar-item/styles.ts
part of #192 
Based on the Ticket NavIconItem [discussion](https://github.com/reapit/elements/issues/164#issuecomment-2463641777), we're slightly agree to have the simple "red dot" within the BottomBarItem component
Design spec https://www.figma.com/design/XJ6qcAV8gHscsUodqJMNEF/Reapit-Elements-production-ready-components?node-id=16-4741&node-type=ellipse&m=dev
> feat: #192 - add simple red dot badge to BottomBarItem

- src/hooks/use-menu/__tests__/index.test.tsx
- src/hooks/use-menu/index.tsx
When a menu item is clicked and configured to keep the menu open, it receives focus. An onBlur handler is set to close the menu when focus moves outside the Menu, causing an issue when focus shifts to the trigger button. The fix is to prevent the onBlur handler from executing if the focus is moving to the trigger button. 
fixes: 
- part of the #163 
fixed result:
> fix: Menu onBlur trigger before trigger click handler

- package.json
- yarn.lock
Closes #160 
We do not need to use `cross-env` in order to support POSIX-like env var assignment in our package scripts. Yarn runs all package scripts within a POSIX-like shell interpreter, thus providing cross-platform support by default.
> task: #160 remove cross-env in favour of Yarn's built-in shell

- src/components/accordion/__tests__/__snapshots__/accordion.atoms.test.tsx.snap
- src/components/accordion/__tests__/__snapshots__/accordion.test.tsx.snap
- src/components/avatar-rectangle/__tests__/__snapshots__/avatar-rectangle.test.tsx.snap
- src/components/breadcrumb/__tests__/__snapshots__/breadcrumb.test.tsx.snap
- src/components/button/__tests__/__snapshots__/button.test.tsx.snap
- src/components/card/__tests__/__snapshots__/card-components.test.tsx.snap
- src/components/deprecated-table/__tests__/__snapshots__/molecules.test.tsx.snap
- src/components/deprecated-table/__tests__/__snapshots__/table.test.tsx.snap
- src/components/drawer/__tests__/__snapshots__/drawer.test.tsx.snap
- src/components/file-input/__tests__/__snapshots__/file-input.test.tsx.snap
- src/components/icon/__tests__/__snapshots__/index.test.tsx.snap
- src/components/input-group/__tests__/__snapshots__/input-group.test.tsx.snap
- src/components/key-value-list/__tests__/__snapshots__/key-value-list.test.tsx.snap
- src/components/mobile-controls/__tests__/__snapshots__/mobile-controls.test.tsx.snap
- src/components/multi-select/__tests__/__snapshots__/multi-select.test.tsx.snap
- src/components/nav-search-button/__tests__/__snapshots__/nav-search-button.test.tsx.snap
- src/components/nav/__tests__/__snapshots__/nav-responsive.test.tsx.snap
- src/components/page-header/__tests__/__snapshots__/page-header.test.tsx.snap
- src/components/pagination/__tests__/__snapshots__/pagination.test.tsx.snap
- src/components/persistent-notification/__tests__/__snapshots__/persistent-notification.test.tsx.snap
- src/components/searchable-dropdown/__tests__/__snapshots__/searchable-dropdown.test.tsx.snap
- src/components/snack/__tests__/__snapshots__/snack.test.tsx.snap
- vite.config.ts
Fixes #220 
#212 missed providing the `icon: true` config to the SVGR plugin when `vite-plugin-svgr` replaced `@svgr/rollup`. This PR adds that config back in to allow icons to be sized correctly.
> fix: #220 ensure svgr plugin provides `icon` option

- src/components/nav-item/styles.ts
- src/components/top-bar/styles.ts
In line with our previous discussion, it is recommended to remove the CSS variable fallback. This will allow us to identify any invalid tokens early on. This pull request also includes fixes to variable names to ensure they are correctly typed.
fixes: #153, #197
> chore: #137 fix css var name and remove fallback value (TopBar)

- src/components/nav-icon-item/nav-icon-item.mdx
- src/components/nav-icon-item/nav-icon-item.stories.tsx
- src/components/nav-icon-item/styles.ts
fixes: #164 
Remove the CSS fallback values for `NavIconItem` component and amend the stories file
> chore: remove fallback css variables `NavIconItem`

- src/components/bottom-bar-item/bottom-bar-item.mdx
- src/components/bottom-bar-item/bottom-bar-item.stories.tsx
- src/components/bottom-bar-item/styles.ts
- src/tokens/payprop/tokens.css
- src/tokens/payprop/tokens.ts
- src/tokens/reapit/tokens.css
- src/tokens/reapit/tokens.ts
- src/tokens/tokens.json
fixes: #192 
- Remove the necessary fallback css variables for `BottomBarItem` 
- Add a new token variable that aligned with the Design System (`--font-size-3xs` with `10px/0.625rem` value)
- Update the stories for `BottomBarItem`
> chore: remove fallback css variables for `BottomBarItem` and update token variable

- src/components/mobile-nav-item/mobile-nav-item.mdx
- src/components/mobile-nav-item/mobile-nav-item.stories.tsx
- src/components/mobile-nav-item/styles.ts
fixes: #206 
addition amendment to not store the fallback CSS variable values in `MobileNavItem`, and amend the story files to able show the correct example on how to use in React usage
> chore: remove fallback css variables for `MobileNavItem` and amend the stories

- src/components/avatar-rectangle/avatar-rectangle.mdx
- src/components/avatar-rectangle/avatar-rectangle.stories.tsx
- src/components/avatar/avatar.mdx
- src/components/avatar/avatar.stories.tsx
This pr is to update `Avatar` and `AvatarRectangle` docs to be more aligned with other existing docs.
updated docs:
https://github.com/user-attachments/assets/13acc7a9-caad-4ada-a2b8-7c4ec45949a8
> chore: v5 update Avatar docs

- src/components/nav/__styles__/index.ts
- src/components/nav/nav-responsive.tsx
- src/components/top-bar/__test__/__snapshots__/top-bar.test.tsx.snap
- src/components/top-bar/__test__/top-bar.test.tsx
- src/components/top-bar/styles.ts
- src/components/top-bar/top-bar.stories.tsx
- src/components/top-bar/top-bar.tsx
this is small part of the app-bar component, which will be used in the top bar navigation.
***app bar (parent)***
***this ticket***
note: this component is just a wrapper to use existing app-switcher in the new `TopBar`
> feat: #253 new app-bar (existing app switcher)

- src/components/menu/menu.mdx
- src/components/menu/menu.stories.tsx
The Menu mdx docs doesn't show the expected code, its apparently because storybook doesn't support to add controls for react compound component, the fix is to remove the controls and the controls will be represented by available stories instead as the previous controls is just boolean.
previous:
fixed:
fixes: #163
new docs:
> fix: #163 fix menu "show code" doesn't show expected code

- src/components/tag/__tests__/__snapshots__/tag.test.tsx.snap
- src/components/tag/__tests__/tag.test.tsx
- src/components/tag/styles.tsx
- src/components/tag/tag.stories.tsx
- src/components/tag/tag.tsx
following the discussion [here](https://github.com/reapit/elements/issues/241#issuecomment-2603753748), we decided to use `as="span"` patten instead of `isStandalone` props pattern
additionally as the term/props changed, I update the exported styles component name
- `ElStandaloneTag` -> `ElTag`
- `ElTag` -> `ElTagGroupItem`
note: react user can still use them as `<Tag />`
fixes: #241
> feat: #241 v5 new Tag component props refactor

- package.json
- src/components/chip/__tests__/chip.test.tsx
- src/components/chip/chip.stories.tsx
- src/components/chip/chip.tsx
- src/components/chip/index.ts
- src/components/chip/styles.ts
- tsconfig.json
- vitest.setup.ts
- yarn.lock
- #258 is introducing a new Chip component
- Elements has an existing Chip component that is considerably different regarding it's intended usage/semantics (it acts as a checkbox)
- #303 deprecated this existing Chip (and Chip Group) component to make room for a new <button>-based version
- Adds the new Chip component (a new ChipGroup component will be added in a separate PR).
**note:** The "Simple Chip" detailed in the Figma designs is currently marked as out-of-scope, so only the "Clearable Chip" has been implemented.
> feat: #258 add new `Chip` component

- src/components/chip-group/__tests__/chip-group-item.tsx
- src/components/chip-group/__tests__/chip-group.test.tsx
- src/components/chip-group/chip-group-item.tsx
- src/components/chip-group/chip-group.stories.tsx
- src/components/chip-group/chip-group.tsx
- src/components/chip-group/styles.ts
- src/components/chip/chip.stories.tsx
- #258 is introducing a new Chip component
- Elements has an existing Chip component that is considerably different regarding it's intended usage/semantics (it acts as a checkbox)
- #303 deprecated this existing Chip (and Chip Group) component to make room for a new <button>-based version
- #304 adds a new Chip component
- Adds a new ChipGroup component.
> feat: #258 add new `ChipGroup` component

- vite.config.ts
Ensure's all peer dependencies are externalised by Vite.
fixes: #317
> chore: Externalise peer dependencies

- .github/workflows/release-prerelease.yml
**Background:**
We recently replaced Jest with Vitest and missed updating the prerelease GitHub workflow to use Vitest.
fixes: #340 `5.0.0-beta.18` release - Replaced jest test script with vitest
> chore: #340 Updated Prerelease test script to vitest

- src/components/side-bar-collapse-button/styles.ts
- src/components/side-bar-menu-group/__tests__/side-bar-menu-group.test.tsx
- src/components/side-bar-menu-group/side-bar-menu-group.molecules.tsx
- src/components/side-bar-menu-group/side-bar-menu-group.tsx
- src/components/side-bar-menu-group/styles.ts
- src/components/side-bar-menu-item/styles.ts
- src/components/side-bar/__test__/side-bar.test.tsx
- src/components/side-bar/side-bar.stories.tsx
- src/components/side-bar/side-bar.tsx
In order to create a new SideBar for the v5 release, this PR, as part of #154, initended to add the accessibility support and keyboard interaction in SideBar.
for this work I referring to https://www.w3.org/WAI/ARIA/apg/patterns/disclosure/examples/disclosure-navigation following the pattern in MobileNav ticket previously.
fixes: #
> feat: #154 SideBar Accessibility (a11y)

- src/components/chip/chip.stories.tsx
- src/components/chip/chip.tsx
- src/components/chip/styles.ts
fixes: #314
- Adds `maxWidth` prop to `Chip`
- Updates `Chip` to use the new design tokens
The image below shows chips with a max width applied. Originally, this was achieved by rendering them inside a parent element that had its own max width. That parent is no longer present and the Chip's are handling the max width themselves.
Here, we can see the Chip's max width handling at work within a Chip group.
> feat: #314 add `maxWidth` prop to `Chip` and use new design tokens

- src/components/avatar/styles.ts
- src/components/badge/styles.ts
- src/components/bottom-bar-item/styles.ts
- src/components/features/styles.ts
- src/components/icon/__styles__/index.ts
- src/components/icon/icon.mdx
- src/components/nav-icon-item/styles.ts
* Icons now inherit colour by default
* unnecessary styling removed now that colour is inherited
fixes (partially): [#281](https://github.com/reapit/elements/issues/281)
> feat: 281 v5 Icon colour inheritance

- src/components/tooltip/__tests__/__snapshots__/tooltip.test.tsx.snap
- src/components/tooltip/tooltip.stories.tsx
- src/components/tooltip/tooltip.tsx
- src/components/tooltip/use-tooltip.ts
- src/helpers/calculatePopoverPosition.ts
fixes: #279 Added helper function to calculate the position of the popover element relative to the trigger.
**Note:**
- The initial usage of this popover is done in the Tooltip component, which uses `createPortal` to position the popover element at the bottom of the body. 
**To do:**
- The current calculation only supports the positioning of the popover element for the 1 level of scrollable element, i.e., window scroll.
- Still need to provide a fix for nested scrollable elements, i.e., Usage of trigger in a scrollable container within a scrollable container. A good example would be a scrollable Table within a scrollable Page.
> feat: #279 Introduce dynamic display of popover element

- src/components/chip-group/chip-group.stories.tsx
- src/components/chip/chip.stories.tsx
- src/components/chip/styles.ts
fixes: #356 and #386 
- Replaces incorrect icon size CSS variables with the correct ones
- Updates the Chip label styles to allow line breaks mid-word
- Adds new stories for Chip and ChipGroup demonstrating correct wrapping behaviour for long words
> fix: #356 #386 Chip style updates

- package.json
- src/storybook/changelog.mdx
fixes: #432 
- Bumpup `main` branch to new version 5.0.0-beta.28 for whenever we are ready for the next release.
- Added changelog section for new releases, devs to update this with all ongoing ticket that gets merged back to `main`
**Note:** I am adding all developers here so that you stay aware of the updated change log for every change you make.
> chore: #432 Bump up beta version to 5.0.0-beta.28

- src/components/bottom-bar/__tests__/__snapshots__/bottom-bar.test.tsx.snap
- src/components/bottom-bar/__tests__/bottom-bar.test.tsx
- src/components/bottom-bar/bottom-bar.atoms.tsx
- src/components/bottom-bar/bottom-bar.stories.tsx
- src/components/menu/__tests__/__snapshots__/menu-popover.test.tsx.snap
- src/components/menu/__tests__/__snapshots__/menu.molecules.test.tsx.snap
- src/components/menu/__tests__/__snapshots__/menu.test.tsx.snap
- src/components/menu/__tests__/menu-popover.test.tsx
- src/components/menu/__tests__/menu.atoms.tests.tsx
- src/components/menu/__tests__/menu.molecules.test.tsx
- src/components/menu/__tests__/menu.test.tsx
- src/components/menu/index.tsx
- src/components/menu/menu-popover.tsx
- src/components/menu/menu.atoms.tsx
- src/components/menu/menu.molecules.tsx
- src/components/menu/menu.stories.tsx
- src/components/menu/menu.tsx
- src/components/menu/styles.ts
- src/components/nav-dropdown-button/nav-dropdown-button.stories.tsx
- src/components/split-button/split-button.stories.tsx
- src/components/table/table-container/table-container.stories.tsx
- src/components/table/table-toolbar/table-toolbar.stories.tsx
- src/components/top-bar/top-bar.stories.tsx
As there is redesign in new v5 Menu #316 . this pr is to refactor existing meu based on a POC that has been discussed [here](https://github.com/reapit/elements/issues/316#issuecomment-2853782912)
note: I've noticed the new behavour regarding the menu group title, I'll address this in a separate PR.
> refactor: #316 new Menu to use props pattern, and new design

- src/components/side-bar/__story__/use-side-bar-context-decorator.tsx
- src/components/side-bar/__story__/use-side-bar-width-decorator.tsx
- src/components/side-bar/side-bar-context.tsx
- src/components/side-bar/submenu-item/__test__/submenu-item.test.tsx
- src/components/side-bar/submenu-item/index.ts
- src/components/side-bar/submenu-item/styles.ts
- src/components/side-bar/submenu-item/submenu-item.stories.tsx
- src/components/side-bar/submenu-item/submenu-item.tsx
- src/components/side-bar/use-side-bar.tsx
- We somehow managed to use component names that don't match what Design are using 🤦 ;
- There's some styles that aren't quite right (e.g. focus outline, SideBar doesn't fill vertical space);
- The components are consistently available via SideBar itself (i.e. inconsistent application of the compound component pattern);
- State management is a little buggy (e.g. an active menu group can be collapsed)
- Refactor component names/responsibilities to match Design
- Fix up styles to ensure correct visual behaviour
- Apply compound component pattern consistently
- Fix bugs in state management
- Improve Storybook documentation for all the components involved in the SideBar
- Adds a new `SideBarContext` object and associated hook that is used to provide the side bar's state and state setters to …
> chore: #443 refactor sidebar components and update styles (part 1)

- src/components/side-bar/__story__/use-side-bar-context-decorator.tsx
- src/components/side-bar/__story__/use-side-bar-width-decorator.tsx
- src/components/side-bar/side-bar-context.tsx
- src/components/side-bar/submenu-item/__test__/submenu-item.test.tsx
- src/components/side-bar/submenu-item/index.ts
- src/components/side-bar/submenu-item/styles.ts
- src/components/side-bar/submenu-item/submenu-item.stories.tsx
- src/components/side-bar/submenu-item/submenu-item.tsx
- src/components/side-bar/submenu/__test__/submenu-list-item.test.tsx
- src/components/side-bar/submenu/__test__/submenu.test.tsx
- src/components/side-bar/submenu/index.ts
- src/components/side-bar/submenu/styles.ts
- src/components/side-bar/submenu/submenu-list-item.tsx
- src/components/side-bar/submenu/submenu.stories.tsx
- src/components/side-bar/submenu/submenu.tsx
- src/components/side-bar/use-side-bar.tsx
- We somehow managed to use component names that don't match what Design are using 🤦 ;
- There's some styles that aren't quite right (e.g. focus outline, SideBar doesn't fill vertical space);
- The components are consistently available via SideBar itself (i.e. inconsistent application of the compound component pattern);
- State management is a little buggy (e.g. an active menu group can be collapsed)
- Refactor component names/responsibilities to match Design
- Fix up styles to ensure correct visual behaviour
- Apply compound component pattern consistently
- Fix bugs in state management
- Improve Storybook documentation for all the components involved in the SideBar
- #450 
- Adds a new `SideBarSubmenu` component. This includes a new subcomponent that wraps the `SideBarSubmenuItem` …
> chore: #443 refactor sidebar components and update styles (part 2)

- src/components/side-bar/menu-group/__test__/menu-group-summary.test.tsx
- src/components/side-bar/menu-group/__test__/menu-group.test.tsx
- src/components/side-bar/menu-group/__test__/use-menu-group-controller.test.tsx
- src/components/side-bar/menu-group/index.ts
- src/components/side-bar/menu-group/menu-group-label-id-context.ts
- src/components/side-bar/menu-group/menu-group-summary.tsx
- src/components/side-bar/menu-group/menu-group.stories.tsx
- src/components/side-bar/menu-group/menu-group.tsx
- src/components/side-bar/menu-group/styles.ts
- src/components/side-bar/menu-group/use-menu-group-controller.ts
- We somehow managed to use component names that don't match what Design are using 🤦 ;
- There's some styles that aren't quite right (e.g. focus outline, SideBar doesn't fill vertical space);
- The components are consistently available via SideBar itself (i.e. inconsistent application of the compound component pattern);
- State management is a little buggy (e.g. an active menu group can be collapsed)
- Refactor component names/responsibilities to match Design
- Fix up styles to ensure correct visual behaviour
- Apply compound component pattern consistently
- Fix bugs in state management
- Improve Storybook documentation for all the components involved in the SideBar
- #450 
- #451 
- #452 
- Adds a new `SideBarMenuGroup` component. This replaces the existing `SideBarMenuGroup` component …
> chore: #443 refactor sidebar components and update styles (part 4)

- src/components/side-bar/menu-list/__test__/menu-list-group.test.tsx
- src/components/side-bar/menu-list/__test__/menu-list-item.test.tsx
- src/components/side-bar/menu-list/__test__/menu-list.test.tsx
- src/components/side-bar/menu-list/index.ts
- src/components/side-bar/menu-list/menu-list-group.tsx
- src/components/side-bar/menu-list/menu-list-item.tsx
- src/components/side-bar/menu-list/menu-list.stories.tsx
- src/components/side-bar/menu-list/menu-list.tsx
- src/components/side-bar/menu-list/styles.ts
- We somehow managed to use component names that don't match what Design are using 🤦 ;
- There's some styles that aren't quite right (e.g. focus outline, SideBar doesn't fill vertical space);
- The components are consistently available via SideBar itself (i.e. inconsistent application of the compound component pattern);
- State management is a little buggy (e.g. an active menu group can be collapsed)
- Refactor component names/responsibilities to match Design
- Fix up styles to ensure correct visual behaviour
- Apply compound component pattern consistently
- Fix bugs in state management
- Improve Storybook documentation for all the components involved in the SideBar
- #450 
- #451 
- #452 
- #453 
- Adds a new `SideBarMenuList` component. This is primary child of the side bar and includes …
> chore: #443 refactor sidebar components and update styles (part 5)

- package.json
- src/storybook/changelog.mdx
fixes: Bumpup beta version to 29
> chore: bumpup beta version to v5.0.0-beta.29

- src/components/side-bar/menu-list/styles.ts
- src/components/side-bar/submenu/styles.ts
- src/storybook/changelog.mdx
fixes: #474
**note:** I have no idea why these user agent styles don't surface in Storybook. When I inspect the side bar list elements in Storybook, the same user agent styles are being applied, but they seem to be having no effect 🤷 Will need to dig into this later I think.
> fix: #474 `SideBar` list elements no longer impacted by user-agent styles

- src/components/nav-search-button/__tests__/__snapshots__/nav-search-button.test.tsx.snap
- src/components/nav-search-button/styles.ts
- src/components/top-bar/__test__/__snapshots__/top-bar.test.tsx.snap
- src/components/top-bar/styles.ts
- src/components/top-bar/top-bar.stories.tsx
- src/components/top-bar/top-bar.tsx
- src/storybook/changelog.mdx
**fixes:** #476
Each of the `TopBar`'s sections will now primarily use container queries to determine whether they should display or not. This allows us to more easily document the responsive behaviour of the `TopBar` in Storybook. With this change, the `NavSearchButton` was also updated to use container queries for its responsive behaviour, though it's likely we'll separate this component into separate mobile and non-mobile components as the current implementation has some issues (see #477)
The new `TopBar` docs look like:
> feat: #476 Use CSS container queries in `TopBar` and `NavSearchButton`

- src/components/top-bar/nav-search-button/nav-search-button.stories.tsx
- src/components/top-bar/nav-search-button/nav-search-button.tsx
- src/components/top-bar/nav-search-button/styles.ts
- src/components/top-bar/nav-search-icon-item/nav-search-icon-item.stories.tsx
- src/components/top-bar/nav-search-icon-item/nav-search-icon-item.tsx
- src/components/top-bar/nav-search/__test__/nav-search.test.tsx
- src/components/top-bar/nav-search/nav-search.stories.tsx
- src/components/top-bar/nav-search/nav-search.tsx
- src/components/top-bar/nav-search/styles.ts
- src/components/top-bar/top-bar.tsx
- src/storybook/changelog.mdx
fixes: #477 
#481 missed some necessary changes. In particular, the components and their styled elements were not renamed to be prefixed with `TopBar`. This PR makes those name changes.
> chore: #477 fix up top bar nav search et al names

- src/components/top-bar/main-nav/__test__/main-nav-list-item.test.tsx
- src/components/top-bar/main-nav/__test__/main-nav-menu-list-item.test.tsx
- src/components/top-bar/main-nav/main-nav-menu-list-item.tsx
- src/components/top-bar/main-nav/main-nav.stories.tsx
- src/components/top-bar/nav-dropdown-button/nav-dropdown-button.tsx
- src/components/top-bar/nav-icon-item/nav-icon-item-anchor.tsx
- src/components/top-bar/nav-icon-item/nav-icon-item-button.tsx
- src/components/top-bar/nav-item/nav-item.stories.tsx
- src/components/top-bar/nav-item/nav-item.tsx
- src/components/top-bar/nav-search-button/nav-search-button.tsx
- src/components/top-bar/secondary-nav/__test__/secondary-nav-list-item.test.tsx
- src/components/top-bar/secondary-nav/__test__/secondary-nav-menu-list-item.test.tsx
- src/components/top-bar/secondary-nav/secondary-nav-menu-list-item.tsx
- src/components/top-bar/top-bar.stories.tsx
- src/components/top-bar/top-bar.tsx
- src/storybook/changelog.mdx
- The Top Bar components are all separated in their own folders. This was largely done because they were implemented in isolation from each other.
- Now, we want to co-locate them all within the `/top-bar` folder.
- We also want to apply the same patterns used in the `SideBar` to these `TopBar` components.
- Move `/nav-item` to `/top-bar/nav-item`
- Move `/nav-dropdown-item` to `/top-bar/nav-dropdown-item`
- Move `/nav-icon-item` to `/top-bar/nav-icon-item`
- Move `/avatar-button` to `/top-bar/avatar-button`
- Add new `TopBar.MainNav` component in `/top-bar/main-nav`
- Add new `TopBar.SecondaryNav` component in `/top-bar/secondary-nav`
- Update docs for all `TopBar` components
Part 7 of #483.
Follows on from #485, #486, #487, #488, #491, and #492.
- Adds extra tests.
- Standardises on …
> chore: #483 add extra tests and tidy up docs

- src/components/link/__tests__/link.test.tsx
- src/components/link/index.ts
- src/components/link/link.stories.tsx
- src/components/link/link.tsx
- src/components/link/styles.ts
- src/storybook/changelog.mdx
- There's a [Link](https://www.figma.com/design/XJ6qcAV8gHscsUodqJMNEF/Reapit-Elements-production-ready-components?node-id=5377-9100&m=dev) component in the Design System;
- It's not available in Elements
- Resolves #513 
- Adds new, simple `Link` component
**note:** <mark>This component was written by Claude in Cursor, using Figma's MCP server to allow Claude to pull design context directly from the design spec.</mark> I then tidied up some of the docs, tests and updated the CSS to use the correct CSS variables (the Figma design spec was not using the latest variables).
> feat: #513 Add `Link` component

- src/components/supplementary-info/styles.ts
Updates the recently added `SupplementaryInfo` and `SupplementaryInfo.Item` components to use the new `font` CSS helper.
> chore: #497 use `font` helper in `SupplementaryInfo`

- package.json
- src/icons/bin/generate-icons.ts
- src/icons/make-icon/__test__/make-icon.test.tsx
- src/icons/make-icon/index.ts
- src/icons/make-icon/make-icon.tsx
- src/icons/make-icon/styles.ts
- src/icons/make-icon/types.ts
- vite.config.ts
- yarn.lock
- We have a bunch of new icons we need to support;
- The existing `Icon` component also has some issues with it's implementation:
- the Icon SVG does not inherit the current colour, which makes it hard to control the colour of the icon via CSS in consumers; and, 
- the Icon component causes all SVGs to be included in the consumer's bundle, even if they only use one.
- We want to deprecate the existing component and create a new icons that can be individually imported by consumers and whose colours are easier to control.
- The old Icon component and SVGs were deprecated in #528 
- The new icon SVGs were added in #529 
Part 3 of #281 
- Adds a new `generate:icons` package script. This script runs a Node.js module, `generate-icons.ts`, that generates icon component modules for each icon SVG …
> feat: Add `generate:icons` script

- src/components/drawer/footer/__test__/footer.test.tsx
- src/components/drawer/footer/footer.stories.tsx
- src/components/drawer/footer/footer.tsx
- src/components/drawer/footer/index.ts
- src/components/drawer/footer/styles.ts
- We're implementing new a `Drawer` component that will not be backwards-compatible with the existing one.
- The existing `Drawer` was deprecated and moved in #516
- The `DrawerBody` component was added in #518 
Part 3 of #145
- Implements the `DrawerFooter` subcomponent.
 pm" src="https://github.com/user-attachments/assets/f4b1d7f2-7f76-4830-a738-8c341df2446f" />
> feat: #145 Add new `DrawerFooter` component

- src/components/drawer/header/__test__/close-button.test.tsx
- src/components/drawer/header/__test__/header.test.tsx
- src/components/drawer/header/close-button.tsx
- src/components/drawer/header/header.stories.tsx
- src/components/drawer/header/header.tsx
- src/components/drawer/header/index.ts
- src/components/drawer/header/styles.ts
- We're implementing new a `Drawer` component that will not be backwards-compatible with the existing one.
- The existing `Drawer` was deprecated and moved in #516
- The `DrawerBody` component was added in #518 
- The `DrawerFooter` component was added in #520 
Part 4 of #145
- Implements the `DrawerHeader` subcomponent and a related `DrawerHeader.CloseButton` component.
> feat: #145 Add new `DrawerHeader` component

- src/components/side-bar/__story__/use-viewport-height-decorator.tsx
- src/components/side-bar/__test__/use-side-bar-controller.test.tsx
- src/components/side-bar/menu-group/index.ts
- src/components/side-bar/side-bar.stories.tsx
- src/components/side-bar/side-bar.tsx
- src/components/side-bar/use-side-bar-controller.ts
- src/storybook/changelog.mdx
- Feedback from SideBar usage in Reapit PM surfaced a misunderstanding regarding the expected behaviour of menu groups within the side bar.
- Currently, menu groups only close automatically if they "lose" the current page (i.e. one of their submenu items was the current page, but no longer is), or if the side bar is collapsed.
- This means manually opened groups remain open, even when other items become the current page (see video below). **This is incorrect.**
https://github.com/user-attachments/assets/c54f2f6d-21d9-48bf-a6af-97485efa0364
- Updates the SideBar component to manually update all menu group's `open` states based on whether they should/should not be open when it observes a change to which item, if any, is marked as the current page. This behaviour still allows more than one …
> feat: Update `SideBar.MenuGroup` behaviour when the current page changes

- .github/workflows/release-prerelease.yml
- .github/workflows/release-prod.yml
- .github/workflows/test-pr.yml
- package.json
- src/storybook/changelog.mdx
- When a consumer tries to import a new icon from v5.0.0-beta.31, there are no types available. Looking at the installed package in the consumer's node_modules, there's no dist/types folder as we would expect.
- Looking at the release-prod and release-prerelease CI pipelines, they only run the build:dist script, not the build:types script.
- Updates package manifest to remove old `main`, `module` and `types` fields. We want to rely solely on `exports`.
- Updates `build:dist` script to `build:lib`
- Updates CI pipelines to use `build` script instead of `build:dist` as the former builds everything, whereas the latter builds only the JS/CSS artefacts
> fix: #542 types are now built properly

- src/components/bottom-bar/item/__tests__/item-anchor.test.tsx
- src/components/bottom-bar/item/__tests__/item-button.test.tsx
- src/components/bottom-bar/item/index.ts
- src/components/bottom-bar/item/item-anchor.stories.tsx
- src/components/bottom-bar/item/item-anchor.tsx
- src/components/bottom-bar/item/item-base.tsx
- src/components/bottom-bar/item/item-button.stories.tsx
- src/components/bottom-bar/item/item-button.tsx
- src/components/bottom-bar/item/styles.ts
- src/components/top-bar/nav-icon-item/nav-icon-item-button.stories.tsx
- src/components/top-bar/nav-icon-item/styles.ts
- We've recently refactored the TopBar and SideBar components so they have a similar structure and consistent application of the compound component pattern.
- We want to do the same for BottomBar.
- Creates a new item component for the bottom bar based on the existing implementation. However, this new implementation takes a similar approach to the top bar's nav icon item components.
> chore: refactor bottom bar item as subcomponent of bottom bar

- src/components/bottom-bar/item/styles.ts
- src/components/bottom-bar/menu-list/__test__/menu-list-item.test.tsx
- src/components/bottom-bar/menu-list/__test__/menu-list-menu-item.test.tsx
- src/components/bottom-bar/menu-list/__test__/menu-list.test.tsx
- src/components/bottom-bar/menu-list/index.ts
- src/components/bottom-bar/menu-list/menu-list-item.tsx
- src/components/bottom-bar/menu-list/menu-list-menu-item.tsx
- src/components/bottom-bar/menu-list/menu-list.stories.tsx
- src/components/bottom-bar/menu-list/menu-list.tsx
- src/components/bottom-bar/menu-list/styles.ts
- We've recently refactored the TopBar and SideBar components so they have a similar structure and consistent application of the compound component pattern.
- We want to do the same for BottomBar.
- New bottom bar item components were added in #545 
- Adds a new menu list component for the bottom bar. This is used to help ensure good a11y for the bottom bar items.
> chore: add new bottom bar menu list as subcomponent of bottom bar

- src/components/app-switcher/app-switcher.stories.tsx
- src/components/app-switcher/nav-icon-button/nav-icon-button.tsx
- src/components/top-bar/nav-icon-item/styles.ts
- Fixes duplicate menu group divider in app switcher menu (this regression occurred when Menu.MenuGroup was update to include a divider itself).
- Fixes invalid CSS variable usage in nav icon items.
**Before**
**After**
> fix: app switcher/nav icon item regressions

- src/components/side-bar/menu-group/menu-group-summary.tsx
- src/components/side-bar/menu-group/menu-group.stories.tsx
- src/components/side-bar/menu-group/styles.ts
- src/components/side-bar/menu-item/menu-item.stories.tsx
- src/components/side-bar/menu-item/styles.ts
- src/components/side-bar/menu-list/menu-list.stories.tsx
- src/components/side-bar/side-bar.stories.tsx
- src/storybook/changelog.mdx
> chore: `SideBar` uses new icons and sizes them correctly

- src/components/top-bar/__test__/__snapshots__/top-bar.test.tsx.snap
- src/components/top-bar/nav-dropdown-button/nav-dropdown-button.tsx
- src/components/top-bar/nav-dropdown-button/styles.ts
- src/components/top-bar/nav-icon-item/nav-icon-item-anchor.stories.tsx
- src/components/top-bar/nav-icon-item/nav-icon-item-button.stories.tsx
- src/components/top-bar/nav-icon-item/styles.ts
- src/components/top-bar/nav-search-button/styles.ts
- src/components/top-bar/nav-search-icon-item/nav-search-icon-item.tsx
- src/components/top-bar/secondary-nav/__test__/secondary-nav-list-item.test.tsx
- src/components/top-bar/secondary-nav/__test__/secondary-nav-menu-list-item.test.tsx
- src/components/top-bar/secondary-nav/secondary-nav.stories.tsx
- src/components/top-bar/top-bar.stories.tsx
- src/storybook/changelog.mdx
> chore: `TopBar` uses new icons and sizes them correctly

- src/components/accordion/accordion-label-id-context.ts
- src/components/accordion/summary/__tests__/summary.test.tsx
- src/components/accordion/summary/index.ts
- src/components/accordion/summary/styles.ts
- src/components/accordion/summary/summary.stories.tsx
- src/components/accordion/summary/summary.tsx
- We're rebuilding our Accordion component for v5
- [Accordion designs](https://www.figma.com/design/XJ6qcAV8gHscsUodqJMNEF/Reapit-Elements-production-ready-components?node-id=2330-2973&m=dev) are ready for dev. 
- The new work will be staged over a number of PRs:
- Part 1: #564
- Part 2: Implement Accordion summary component **(this PR)**
- Part 3: Implement Accordion component
- Adds a new `Accordion.Summary` component.
> feat: Add new `Accordion.Summary` component

- src/components/button/__tests__/button-base.test.tsx
- src/components/button/button-base.tsx
- src/components/button/spinner.svg
- src/components/button/styles.ts
- The existing v5 Elements button has been deprecated in Figma and a new Button designed.
- To align Elements, we're going to do the same thing: deprecated the current Button and implement a new replacement.
- This work will be done in the following stages:
- Part 1: #572 
- **Part 2: Add new foundational ButtonBase component (this PR)**
- Part 3: Add new Button and AnchorButton components
- Adds a new ButtonBase component. This will be the foundation of the new Button and AnchorButton components that will be added in Part 3.
The following images show the storybook docs added for Button in Part 3 (#574):
> feat: Add new `ButtonBase` component

- src/components/badge/styles.ts
- src/components/button/button-base.tsx
- src/components/button/styles.ts
- src/components/chip-group/chip-group.stories.tsx
- src/components/chip-group/styles.ts
- src/components/chip/__tests__/chip.test.tsx
- src/components/chip/chip.stories.tsx
- src/components/chip/chip.tsx
- src/components/chip/styles.ts
- src/components/tag-group/styles.ts
- src/icons/make-icon/styles.ts
- src/storybook/changelog.mdx
- Aligns `Chip` interface with new `Button` regarding `disabled` and `aria-disabled`.
- Updates `Chip` styles to ensure correct minimum height (fixes #580), update it to use the new `font` helper, the correct focus outline styles (outline instead of box-shadow) and use the new icons (instead of the deprecated icons).
- Updates `Badge`, `TagGroup` and new icons to use `vertical-align: middle` in inline and inline-block layouts. This has no effect in flex or grid layouts.
> chore: align Chip with Button and tweak styles in other components

- src/components/page-header/title/__tests__/title.test.tsx
- src/components/page-header/title/index.ts
- src/components/page-header/title/styles.ts
- src/components/page-header/title/title.stories.tsx
- src/components/page-header/title/title.tsx
- There's new [PageHeader](https://www.figma.com/design/XJ6qcAV8gHscsUodqJMNEF/Reapit-Elements-production-ready-components?node-id=2330-2964&m=dev&focus-id=10113-8278) designs for Elements;
- The existing `PageHeader` relies on "prop configuration" to display content rather than the composition of atomic components.
- We want to deliver the new PageHeader with a compositional API, so we want to deprecate the existing one and deliver a new one.
- Part 1: #594
- **Part 2: Add new `PageHeader.Title` (this PR)**
- Adds a new `PageHeader.Title` component.
> feat: Add new `PageHeader.Title` component

- src/components/page-header/subtitle/__tests__/subtitle.test.tsx
- src/components/page-header/subtitle/index.ts
- src/components/page-header/subtitle/styles.ts
- src/components/page-header/subtitle/subtitle.stories.tsx
- src/components/page-header/subtitle/subtitle.tsx
- There's new [PageHeader](https://www.figma.com/design/XJ6qcAV8gHscsUodqJMNEF/Reapit-Elements-production-ready-components?node-id=2330-2964&m=dev&focus-id=10113-8278) designs for Elements;
- The existing `PageHeader` relies on "prop configuration" to display content rather than the composition of atomic components.
- We want to deliver the new PageHeader with a compositional API, so we want to deprecate the existing one and deliver a new one.
- Part 1: #594
- Part 2: #596 
- **Part 3: Add new `PageHeader.Subtitle` (this PR)**
- Adds a new `PageHeader.Subtitle` component.
> feat: Add new `PageHeader.Subtitle` component

- src/components/features/styles.ts
#598 missed the removal of the user-agent `margin` applied to `dl` elements. This PR fixes that omission.
> chore: remove margin on `Features`

- src/components/deprecated-nav/__styles__/index.ts
- src/storybook/changelog.mdx
#551 introduced linting and, as a result, made a number of CSS changes to existing components to resolve lint issues now being surfaces. Once of these changes was the re-ordering of CSS blocks for the `DeprecatedNav` component. These blocks had the same specificity, so the change in order resulted in a different block's properties gaining precedence, thus causing the visual regression.
This PR fixes this issue while still adhering to the CSS lint rules now at play (specifically, the [no-descending-specificity](https://stylelint.io/user-guide/rules/no-descending-specificity) rule).
| Before | After |
| ------ | ----- |
| <img width="1010" alt="Screenshot 2025-07-08 at 11 17 29 pm" src="https://github.com/user-attachments/assets/eaf0b0b2-199b-42d5-b7c8-279b16ff72a5" /> | <img width="1015" …
> fix: #597 `DeprecatedNav` alignment regression

- src/storybook/changelog.mdx
> chore: update changelog

- src/components/primary-tabs/__tests__/primary-tabs-item.test.tsx
- src/components/primary-tabs/__tests__/primary-tabs.test.tsx
- src/components/primary-tabs/index.ts
- src/components/primary-tabs/primary-tabs-item.tsx
- src/components/primary-tabs/primary-tabs.stories.tsx
- src/components/primary-tabs/primary-tabs.tsx
- src/components/primary-tabs/styles.ts
- src/components/primary-tabs/tab/__tests__/tab.test.tsx
- src/components/primary-tabs/tab/index.ts
- src/components/primary-tabs/tab/styles.ts
- src/components/primary-tabs/tab/tab.stories.tsx
- src/components/primary-tabs/tab/tab.tsx
- src/storybook/changelog.mdx
- The existing Tabs component is already deprecated. It is named `Tabs`.
- There are three new tab components in the Design System: PrimaryTabs, SecondaryTabs and FolderTabs. We will deliver new v5 components for each of these, rather than a single Tabs component with variants, because there is considerable visual difference between them.
- This means we do not need to rename the deprecated Tabs component to DeprecatedTabs, as we do not need its current name for the new components.
- Adds a new `PrimaryTabs` component.
> feat: Add new `PrimaryTabs` component

- src/components/split-button/__tests__/split-button-menu.test.tsx
- src/components/split-button/__tests__/split-button.test.tsx
- src/components/split-button/index.ts
- src/components/split-button/menu-button/menu-button.tsx
- src/components/split-button/split-button-menu.tsx
- src/components/split-button/split-button.stories.tsx
- src/components/split-button/split-button.tsx
- src/components/split-button/styles.ts
- src/storybook/changelog.mdx
- We recently refactored our `Button` component. This resulted in the existing Button being deprecated and renamed to `DeprecatedButton`.
- This impacted our existing `SplitButton` component, which is built on top of the old, now deprecated Button.
- We need to refactor `SplitButton` to work with the new `Button` component. We will do this over the following stages:
- #616 
- #617 
- #618 
- **Part 4: Implement new `SplitButton` (this PR)**
- Adds new `SplitButton` component
> feat: Add `SplitButton` component

- src/storybook/changelog.mdx
- src/utils/breakpoints/__tests__/breakpoints.test.ts
- src/utils/breakpoints/__tests__/conditions.test.ts
- src/utils/breakpoints/breakpoints.ts
- src/utils/breakpoints/conditions.ts
- src/utils/breakpoints/index.mdx
- src/utils/breakpoints/index.ts
- src/utils/match-media/__tests__/match-media.test.tsx
- src/utils/match-media/__tests__/use-match-media.test.tsx
- src/utils/match-media/index.ts
- src/utils/match-media/match-media.stories.tsx
- src/utils/match-media/match-media.tsx
- src/utils/match-media/use-match-media.mdx
- src/utils/match-media/use-match-media.ts
- src/utils/url-search-params/to-map.mdx
- src/utils/url-search-params/to-url-search-params.mdx
- We have deprecated breakpoint names, and a deprecated `useMediaQuery` hook, that all need replacing.
- We want to introduce new breakpoint variables per the Design System's new names and allow them to be used for media and container queries.
- We want to introduce new helper functions for build width-based queries/conditions for use with media and container queries.
- We want to introduce a new component, `MatchMedia`, and a new hook, `useMatchMedia` that leverage the browser's `matchMedia` API (rather than the custom approach used in the deprecated hook).
Does all of the above...
> feat: Add new `MatchMedia`, `useMatchMedia` and other breakpoint helpers

- src/core/dialog/footer/__tests__/footer.test.tsx
- src/core/dialog/footer/footer.stories.tsx
- src/core/dialog/footer/footer.tsx
- src/core/dialog/footer/index.ts
- src/core/dialog/footer/styles.ts
- The `Dialog` component has received Design updates; we need to update our implementation to match.
- The work will be done over a series of PRs:
- Part 1: Add new `Dialog.Footer`
- Part 2: Add new `Dialog.Body`
- Part 3: Add new `Dialog.Header`
- Part 4: Update `Dialog` to use new subcomponents.
- Adds a new `Dialog.Footer` subcomponent. It is not used or exposed yet, though docs are included for it.
> feat: Add new `Dialog.Footer`

- src/core/drawer/body/styles.ts
- src/core/drawer/footer/styles.ts
- src/core/drawer/header/styles.ts
- src/core/drawer/styles.ts
The current drawer styles apply CSS properties specific for the transition even when the user prefers reduced motion. This PR moves those transition-related styles inside the `prefers-reduced-motion: no-preference` media query so they are only applied when transitions will be used.
This PR also updates the elements used by the `Drawer.Body`, `Drawer.Footer` and `Drawer.Header` components.
> chore: update drawer transition

- package.json
- src/storybook/changelog.mdx
The package manifest defined the `./reset.css` entry point as `./public/reset.css` instead of `./assets/reset.css`.
> fix: Update `package.json` `reset.css` entry point

- package.json
- src/polyfills/css-anchor-positioning/__tests__/is-css-anchor-positioning-supported.test.ts
- src/polyfills/css-anchor-positioning/__tests__/polyfill.test.ts
- src/polyfills/css-anchor-positioning/index.ts
- src/polyfills/css-anchor-positioning/is-css-anchor-positioning-supported.ts
- src/polyfills/css-anchor-positioning/polyfill.ts
- yarn.lock
- We're about to refactor our Menu and Tooltip components, with a focus on enhancing their positioning capability.
- [CSS Anchor Positioning](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_anchor_positioning) is not yet supported by all the major browsers (at time of writing, Safari 26 has preview support and Firefox has no support).
- Without CSS anchor positioning, we would have to buy into a significant amount of complexity to implement an equally capable JavaScript positioning solution.
- OddBird provide a [CSS Anchor Positioning polyfill](https://anchor-positioning.oddbird.net/) that allows CSS anchor positioning to be used on browsers that don't yet natively support it.
- Implements a new helper, `applyCSSAnchorPositioningPolyfill`, that allows anchor positioning CSS to be …
> feat: Add CSS anchor positioning polyfill

- src/core/menu/item/__tests__/anchor-item.test.tsx
- src/core/menu/item/__tests__/item-base.test.tsx
- src/core/menu/item/__tests__/item.test.tsx
- src/core/menu/item/anchor-item.tsx
- src/core/menu/item/index.ts
- src/core/menu/item/item-base.tsx
- src/core/menu/item/item.stories.tsx
- src/core/menu/item/item.tsx
- src/core/menu/item/styles.ts
- src/deprecated/breadcrumb/breadcrumb.mdx
- The existing Menu component is partially complete, but has a number of issues related to it (focus outline of items is clipped, menu item prop interface incomplete, inadequate positioning w.r.t anchor, reliant on div container which interferes with the layout of the trigger and more)
- We need to deliver a more solid foundation for Menu's while also supporting the updated Menu design requirements.
- To do this, we'll deprecate the existing Menu and implement a new one. This will allow consumers (including other Elements components) to gradually migrate to the new version.
- Previous work in this series:
- #636 
- Adds new `MenuItem` and `AnchorMenuItem` components.
> feat: Add new `MenuItem` and `AnchorMenuItem` components

- src/core/menu/group/__tests__/menu-group.test.tsx
- src/core/menu/group/index.ts
- src/core/menu/group/menu-group.stories.tsx
- src/core/menu/group/menu-group.tsx
- src/core/menu/group/styles.ts
- src/core/menu/item/__tests__/anchor-item.test.tsx
- src/core/menu/item/__tests__/item-base.test.tsx
- src/core/menu/item/__tests__/item.test.tsx
- src/core/menu/item/item-base.tsx
- src/core/menu/item/item.stories.tsx
- src/core/menu/item/item.tsx
- src/core/menu/item/styles.ts
- The existing Menu component is partially complete, but has a number of issues related to it (focus outline of items is clipped, menu item prop interface incomplete, inadequate positioning w.r.t anchor, reliant on div container which interferes with the layout of the trigger and more)
- We need to deliver a more solid foundation for Menu's while also supporting the updated Menu design requirements.
- To do this, we'll deprecate the existing Menu and implement a new one. This will allow consumers (including other Elements components) to gradually migrate to the new version.
- Previous work in this series:
- #636 
- #637 
- Adds new `MenuGroup` component
**note:** We have not taken the approach of rendering the menu group's items as list items in a list, as we have done for …
> feat: Add new `MenuGroup` component

- src/polyfills/css-anchor-positioning/__tests__/is-css-anchor-positioning-supported.test.ts
- src/polyfills/css-anchor-positioning/is-css-anchor-positioning-supported.ts
- src/storybook/changelog.mdx
- src/utils/popover/__tests__/__snapshots__/map-placement-to-css.test.ts.snap
- src/utils/popover/__tests__/build-anchor-positioning-css.test.ts
- src/utils/popover/__tests__/get-popover-trigger-props.test.ts
- src/utils/popover/__tests__/map-placement-to-css.test.ts
- src/utils/popover/__tests__/popover.test.tsx
- src/utils/popover/build-anchor-positioning-css.ts
- src/utils/popover/get-popover-trigger-props.ts
- src/utils/popover/index.ts
- src/utils/popover/map-placement-to-css.ts
- src/utils/popover/popover.stories.tsx
- src/utils/popover/popover.tsx
- src/utils/popover/styles.ts
- The existing Menu component is partially complete, but has a number of issues related to it (focus outline of items is clipped, menu item prop interface incomplete, inadequate positioning w.r.t anchor, reliant on div container which interferes with the layout of the trigger and more)
- We need to deliver a more solid foundation for Menu's while also supporting the updated Menu design requirements.
- To do this, we'll deprecate the existing Menu and implement a new one. This will allow consumers (including other Elements components) to gradually migrate to the new version.
- Previous work in this series:
- #636 
- #637 
- #640 
- Adds new `Popover` component. This will for the foundation of the new Menu component (and later, the Tooltip).
> feat: Add new Popover utility component

- src/core/menu/divider/__tests__/divider.test.tsx
- src/core/menu/divider/divider.stories.tsx
- src/core/menu/divider/divider.tsx
- src/core/menu/divider/index.ts
- src/core/menu/divider/styles.ts
- The existing Menu component is partially complete, but has a number of issues related to it (focus outline of items is clipped, menu item prop interface incomplete, inadequate positioning w.r.t anchor, reliant on div container which interferes with the layout of the trigger and more)
- We need to deliver a more solid foundation for Menu's while also supporting the updated Menu design requirements.
- To do this, we'll deprecate the existing Menu and implement a new one. This will allow consumers (including other Elements components) to gradually migrate to the new version.
- Previous work in this series:
- #636 
- #637 
- #640 
- #641 
- Adds new `MenuDivider` component.
> feat: Add new `MenuDivider`

- src/core/menu/menu.stories.tsx
- src/core/menu/menu.tsx
- src/core/menu/styles.ts
- src/utils/popover/__tests__/popover.test.tsx
- src/utils/popover/popover.stories.tsx
- src/utils/popover/popover.tsx
- src/utils/popover/styles.ts
The new Menu's border radius is not working as expected. The popover's background is not transparent as intended, perhaps because of the box-shadow? 🤷 Either way, we need to shift the border-radius from the ElMenuContent styled element to the popover element itself.
> fix: border radius on Menu

- src/core/label-text/styles.ts
- src/core/pagination/styles.ts
- src/core/table/table-container/styles.ts
- src/core/table/table-toolbar/styles.ts
- src/core/textarea/styles.ts
- src/core/top-bar/main-nav/styles.ts
- src/core/top-bar/secondary-nav/styles.ts
- src/deprecated/avatar/__styles__/index.ts
- src/deprecated/button/styles.ts
- src/deprecated/card/__styles__/index.ts
- src/deprecated/form-layout/__styles__/index.ts
- src/deprecated/input/__styles__/index.ts
- src/deprecated/layout/styles.ts
- src/deprecated/multi-select/__styles__/index.ts
- src/deprecated/nav/__styles__/index.ts
- src/deprecated/page-header/__styles__/index.ts
- src/deprecated/persistent-notification/__styles__/index.ts
- src/deprecated/split-button/styles.ts
- src/deprecated/status-indicator/__styles__/index.ts
- src/deprecated/table/__styles__/index.ts
- src/deprecated/tabs/styles.ts
- src/deprecated/tile/__styles__/index.ts
- src/deprecated/toggle/__styles__/index.ts
- src/deprecated/typography/__styles__/index.ts
- src/styles/deprecated-intent.ts
- src/styles/deprecated-states.ts
Linaria 0.7.0 does not play nicely with empty classes/styled elements, sometimes throwing build errors like `[wyw-in-js] Cannot use 'in' operator to search for 'initialCode' in undefined`. There is an [issue raised](https://github.com/Anber/wyw-in-js/issues/144) and a [PR to fix it](https://github.com/Anber/wyw-in-js/pull/147), but it remains unmerged.
This PR adds a CSS comment to all currently empty classes/styled elements. This appears to avoid the build issues, though given the build issues are intermittent anyway, it's hard to know if this will stand up over time.
> fix: Avoid empty classes/styled elements

- src/core/menu/menu.tsx
- src/core/menu/styles.ts
- src/core/tooltip/__tests__/get-tooltip-trigger-props.test.ts
- src/core/tooltip/__tests__/is-tooltip-needed.test.ts
- src/core/tooltip/__tests__/tooltip.test.tsx
- src/core/tooltip/__tests__/use-tooltip-controller.test.tsx
- src/core/tooltip/get-tooltip-trigger-props.ts
- src/core/tooltip/index.ts
- src/core/tooltip/is-tooltip-needed.ts
- src/core/tooltip/styles.ts
- src/core/tooltip/tooltip.stories.tsx
- src/core/tooltip/tooltip.tsx
- src/core/tooltip/use-tooltip-controller.ts
- src/deprecated/tooltip/tooltip.stories.tsx
- src/storybook/changelog.mdx
- src/utils/popover/index.ts
- src/utils/popover/popover.tsx
- We want to leverage the new Popover utility component for our tooltips.
- The existing Tooltip component has a number of API choices that make it awkward to maintain backwards compatibility with if it's internal implementation moves to Popover.
- Thus we want to deprecate the existing Tooltip and implement a new replacement.
- Previous work includes:
- #649 
- Adds new `Tooltip` component.
> feat: Add new `Tooltip`

- src/core/app-switcher/__tests__/app-switcher.test.tsx
- src/core/app-switcher/app-avatar/__test__/__snapshots__/app-avatar.test.tsx.snap
- src/core/app-switcher/app-avatar/app-avatar.tsx
- src/core/app-switcher/app-switcher.stories.tsx
- src/core/app-switcher/app-switcher.tsx
- src/core/app-switcher/explore-menu-group/__test__/__snapshots__/explore-menu-group.test.tsx.snap
- src/core/app-switcher/explore-menu-group/explore-menu-group.tsx
- src/core/app-switcher/index.ts
- src/core/app-switcher/menu-item/__test__/__snapshots__/menu-item.test.tsx.snap
- src/core/app-switcher/nav-icon-button/nav-icon-button.tsx
- src/core/app-switcher/styles.ts
- src/core/app-switcher/your-apps-menu-group/__test__/__snapshots__/your-apps-menu-group.test.tsx.snap
- src/core/app-switcher/your-apps-menu-group/your-apps-menu-group.tsx
- src/core/split-button/__tests__/split-button-menu.test.tsx
- src/core/split-button/menu-button/__tests__/menu-button.test.tsx
- src/core/split-button/menu-button/menu-button.tsx
- src/core/split-button/menu-button/styles.ts
- src/core/split-button/split-button-menu.tsx
- src/core/split-button/split-button.stories.tsx
- src/core/top-bar/main-nav/__tests__/main-nav-menu-list-item.test.tsx
- src/core/top-bar/main-nav/main-nav-menu-list-item.tsx
- src/core/top-bar/main-nav/main-nav.stories.tsx
- src/core/top-bar/nav-dropdown-button/nav-dropdown-button.stories.tsx
- src/core/top-bar/nav-dropdown-button/nav-dropdown-button.tsx
- src/core/top-bar/nav-dropdown-button/styles.ts
- src/core/top-bar/nav-icon-item/nav-icon-item-button.tsx
- src/core/top-bar/secondary-nav/__tests__/secondary-nav-menu-list-item.test.tsx
- src/core/top-bar/secondary-nav/secondary-nav-menu-list-item.tsx
- src/utils/popover/__tests__/get-popover-trigger-props.test.ts
- src/utils/popover/get-popover-trigger-props.ts
- We recently implemented a new `Menu` component.
- Many existing core components are still using `DeprecatedMenu`.
- We need to update the new components to use the new one.
- Updates the remaining core components using `DeprecatedMenu` to now use `Menu`
> chore: use new `Menu` in core components

- src/core/checkbox/checkbox.tsx
- src/storybook/changelog.mdx
The Checkbox does not currently support consumer-supplied refs. This PR updates it to use `forwardRef`.
Also scouted some changes to the change log that were missed in recent commits.
> fix: `Checkbox` now supports consumer-supplied refs

- .github/workflows/release-prerelease.yml
- package.json
- src/core/menu/divider/styles.ts
- src/core/side-bar/menu-group/styles.ts
- src/core/side-bar/menu-item/styles.ts
- src/core/top-bar/main-nav/main-nav-menu-list-item.tsx
- src/icons/__tests__/__snapshots__/icons.test.tsx.snap
- src/index.ts
- src/storybook/changelog.mdx
- Bumps package version.
- Resolve regression in `SideBar.Item` and `SideBar.MenuGroupSummary` text and icon alignment. This was impacting Reapit PM.
- Prevent user-agent styles impacting `Menu.Divider`. This was impacting Reapit PM.
- Prerelease pipeline error in `Create Pull Request For Version` step.
- Tweaks `TopBar.NavMenuItem` menu placement from `bottom-end` to `bottom-start`.
> fix: minor post-release issues

- src/core/side-bar/__tests__/use-side-bar-controller.test.tsx
- src/core/side-bar/menu-item/menu-item.tsx
- src/core/side-bar/side-bar.tsx
- src/core/side-bar/use-side-bar-controller.ts
> fix: #662 side bar menu groups no longer open when side bar is collapsed

- src/core/top-bar/avatar-button/avatar-button.stories.tsx
- src/core/top-bar/avatar-button/avatar-button.tsx
- src/core/top-bar/avatar-button/styles.ts
- src/core/top-bar/avatar-menu/__tests__/avatar-menu.test.tsx
- src/core/top-bar/avatar-menu/avatar-menu.stories.tsx
- src/core/top-bar/avatar-menu/avatar-menu.tsx
- src/core/top-bar/avatar-menu/index.ts
- src/core/top-bar/index.ts
- src/core/top-bar/top-bar.tsx
- src/storybook/changelog.mdx
Adds a new `TopBar.AvatarMenu` component. This provides a more convenient option for consumers than direct use of `TopBar.AvatarButton` and `Menu`.
Plus:
- Fixes `TopBar.AvatarButton` so that it supports `Menu.getTriggerProps`.
- Exports missing top bar components.
> feat: new `TopBar.AvatarMenu`

- src/core/tooltip/__tests__/use-tooltip-controller.test.tsx
- src/core/tooltip/use-tooltip-controller.ts
- src/storybook/changelog.mdx
Fixes small bug with Tooltip display behaviour.
`Tooltip` only shows when the trigger is focused through keyboard navigation. Previously, it would show when the trigger was programmatically focused, such as when a menu controlled by the trigger was closed.
> fix: `Tooltip` only shows on focus when tabbed to

- src/core/text/__tests__/text.test.tsx
- src/core/text/styles.ts
- src/core/text/text.stories.tsx
- src/core/text/text.tsx
- src/storybook/changelog.mdx
> feat: `Text` supports new `overflow='truncate'` prop

- src/core/badge/badge.stories.tsx
- src/core/badge/styles.ts
- src/storybook/changelog.mdx
What it says on the tin. Badge labels will no longer wrap.
> fix: `Badge` label will no longer wrap

- src/core/status-indicator/status-indicator.stories.tsx
- src/core/status-indicator/styles.ts
- src/storybook/changelog.mdx
> fix: `StatusIndicator` text no longer wraps

- src/lab/search-input/__tests__/search-input.test.tsx
- src/lab/search-input/search-input.tsx
> chore: `SearchInput` `onSearch` prop changed to `unstable_onSearch`

- src/core/chip-group/__tests__/chip-group.test.tsx
- src/core/chip-group/chip-group.stories.tsx
- src/core/chip-group/chip-group.tsx
- src/core/chip-group/styles.ts
- src/core/chip/__tests__/chip.test.tsx
- src/core/chip/chip.stories.tsx
- src/core/chip/chip.tsx
- src/core/chip/styles.ts
- src/core/tag-group/__tests__/tag-group.test.tsx
- src/core/tag-group/styles.ts
- src/core/tag-group/tag-group.stories.tsx
- src/core/tag-group/tag-group.tsx
- src/core/tag/styles.ts
- src/storybook/changelog.mdx
- `ChipGroup` current supports an `overflow: 'scroll' | 'wrap'`. This allows consumes to either have items wrap to additional lines or to remain on a single line and overflow with scrolling.
- `TagGroup` items currently wrap to additional lines, but we need to support the ability to disable this wrapping behaviour and, optionally, overflow with scrolling. That is, we need more flexibility than we have with `ChipGroup`.
- A single `overflow` prop is insufficient; better, would be to split the concerns over two props: `flow: 'wrap' | 'nowrap'` and `overflow: 'auto' | 'hidden'`.
- Aligns `TagGroup` and `ChipGroup` interfaces:
- `ChipGroup` no longer supports `overflow: 'scroll' | 'wrap'`. Instead, it now supports `flow: 'wrap' | 'nowrap'` and `overflow: 'auto' | 'hidden'`. To migrate, …
> chore: align `TagGroup` and `ChipGroup`

- src/core/table/primary-action/__tests__/primary-action.test.tsx
- src/core/table/primary-action/__tests__/primary-button.test.tsx
- src/core/table/primary-action/index.ts
- src/core/table/primary-action/primary-action-button.tsx
- src/core/table/primary-action/primary-action.stories.tsx
- src/core/table/primary-action/primary-action.tsx
- src/core/table/primary-action/styles.ts
> feat: Add new `TableRowPrimaryAction`

- src/core/table/primary-data/__tests__/primary-data.test.tsx
- src/core/table/primary-data/index.ts
- src/core/table/primary-data/primary-data.stories.tsx
- src/core/table/primary-data/primary-data.tsx
- src/core/table/primary-data/styles.ts
> feat: Add new `TableCellPrimaryData`

- src/core/table/double-line-layout/__tests__/double-line-layout.test.tsx
- src/core/table/double-line-layout/double-line-layout.stories.tsx
- src/core/table/double-line-layout/double-line-layout.tsx
- src/core/table/double-line-layout/index.ts
- src/core/table/double-line-layout/styles.ts
> feat: Add new `TableCellDoubleLineLayout`

- src/core/table/__story__/use-table-decorator.tsx
- src/core/table/body-cell/__test__/body-cell.test.tsx
- src/core/table/body-cell/body-cell.stories.tsx
- src/core/table/body-cell/body-cell.tsx
- src/core/table/body-cell/index.ts
- src/core/table/body-cell/styles.ts
> feat: Add new `TableBodyCell`

- src/core/table/body-cell/__test__/body-cell.test.tsx
- src/core/table/body-cell/body-cell.stories.tsx
- src/core/table/body-cell/body-cell.tsx
- src/core/table/body-row/body-row.stories.tsx
- src/core/table/body-row/styles.ts
- #718 added a new `TableBodyCell`.
- It required consumers to manually supply `scope="row"` when using `as="th"`.
- But, this should be handled automatically for consumers.
- Updates `TableBodyCell` to auto apply `scope="row"` when `as="th"`
- Updates tests to no longer rely on stories, because `composeStories` wasn't decorating the stories correctly leading to DOM nesting errors under test.
> chore: update `TableBodyCell` to auto apply `scope="row"`

- src/core/table/__story__/table-wrapper.tsx
- src/core/table/__story__/use-table-decorator.tsx
- src/core/table/body-cell/__tests__/body-cell.test.tsx
- src/core/table/body-row/__tests__/body-row.test.tsx
- src/core/table/body/__tests__/body.test.tsx
- src/core/table/more-actions/styles.ts
Many of the unit tests for our table atoms, whether they're using `composeStories` or not, aren't rendering the subjects under test within a valid table DOM structure. This results in `validateDOMNesting` errors being present in the test output.
This PR extracts the table wrapper setup from `useTableDecorator` to a separate `buildTableWrapper` helper which is used directly by the unit tests.
> chore: ensure valid DOM in table unit tests

- src/core/table/__story__/table-wrapper.tsx
- src/core/table/header-cell/__tests__/header-cell.test.tsx
- src/core/table/header-cell/header-cell.stories.tsx
- src/core/table/header-cell/header-cell.tsx
- src/core/table/header-cell/index.ts
- src/core/table/header-cell/styles.ts
- src/core/table/sort-button/index.ts
> feat: Add new `TableHeaderCell`

- src/core/table/__story__/table-wrapper.tsx
- src/core/table/header-row/__tests__/header-row.test.tsx
- src/core/table/header-row/header-row.stories.tsx
- src/core/table/header-row/header-row.tsx
- src/core/table/header-row/index.ts
- src/core/table/header-row/styles.ts
> feat: Add new `TableHeaderRow`

- src/core/table/__story__/table-wrapper.tsx
- src/core/table/head/__tests__/head.test.tsx
- src/core/table/head/head.stories.tsx
- src/core/table/head/head.tsx
- src/core/table/head/index.ts
- src/core/table/head/styles.ts
> feat: Add new `TableHead`

- src/core/table/header-cell/__tests__/header-cell.test.tsx
- src/core/table/header-cell/header-cell.tsx
- src/storybook/changelog.mdx
Header cells are not permitted to have empty content: https://dequeuniversity.com/rules/axe/4.8/empty-table-header?application=axeAPI
> fix: `Table.HeaderCell` renders as a `td` when it has no cell content

- src/core/input/__tests__/input.test.tsx
- src/core/input/checkbox/__tests__/checkbox.test.tsx
- src/core/input/checkbox/checkbox.tsx
- src/core/input/checkbox/index.ts
- src/core/input/checkbox/styles.ts
- src/core/input/index.ts
- src/core/input/input.stories.tsx
- src/core/input/input.tsx
- src/storybook/changelog.mdx
- We're delivering new core table components and we require a checkbox component to enable row selection.
- The existing Checkbox component includes a lot of functionality that is simply irrelevant to row selection (such as visual labels and supplementary information).
- Ideally, we want a thin wrapper around an `<input type="checkbox">` so that we have the correct checkbox visual appearance, without any of the additional label handling. That way, this low-level input component can be used internally by Checkbox and our row selection table component.
- Adds a new `Input` component with support for `type="checkbox"`. This component will be expanded to support other input types and represents the lowest-level styled input component in Elements.
> feat: add `Input` with support for `type='checkbox'`

- src/core/input/checkbox/styles.ts
The new `InputCheckbox` component (used internally by `Input`) based it's focus outline styles on the Checkbox component in Figma, but these styles are non-standard. This PR updates them to match the focus outline styles shown for the row selection checkboxes in the table design in Figma.
> fix: `InputCheckbox` focus outline

- src/core/tag/styles.ts
- src/storybook/changelog.mdx
> fix: `Tag` text now has the correct colour

- src/core/chip-select/chip-select.stories.tsx
- src/core/chip-select/chip-select.tsx
- src/core/chip-select/chip/__tests__/chip.test.tsx
- src/core/chip-select/chip/__tests__/determine-next-controlled-state.test.ts
- src/core/chip-select/chip/chip.stories.tsx
- src/core/chip-select/chip/chip.tsx
- src/core/chip-select/chip/determine-next-controlled-state.ts
- src/core/chip-select/chip/index.ts
- src/core/chip-select/chip/is-exclusive-option.ts
- src/core/chip-select/chip/maybe-deselect-other-options.ts
- For part 1, see #757 
- For part 2, see #758 
- Part 3 of #424 
- Adds new `ChipSelect.determineNextControlledState` helper for consumers that must control the checked state of the chip select's options.
- Added new story to `ChipSelect` docs.
> feat: add `ChipSelect.determineNextControlledState`

- src/core/chip-select/chip-select.stories.tsx
- src/core/chip-select/chip-select.tsx
- src/core/chip-select/index.ts
- src/storybook/changelog.mdx
- Adds links to example integrations with [Formik](https://codesandbox.io/p/sandbox/eloquent-julien-hkgfgy) and [React Hook Form](https://codesandbox.io/p/sandbox/strange-lederberg-thzzwv) to the `ChipSelect` docs.
- Small scout to export the chip select's context, as well as make it available via `ChipSelect.Context` and `ChipSelect.useContext`.
> chore: add links to form integration examples to `ChipSelect` docs

- src/core/chip-select/chip/__tests__/chip.test.tsx
- src/core/chip-select/chip/chip.stories.tsx
- src/core/chip-select/chip/chip.tsx
- src/core/chip-select/chip/styles.ts
- Adds support for `readOnly` to `ChipSelectChip`.
> feat: add `readOnly` support to `ChipSelect`

- figma.config.json
- src/core/button/button.figma.tsx
- src/core/divider/divider.figma.tsx
- src/core/empty-data/action/action-button.tsx
- src/core/empty-data/action/action.tsx
- src/core/empty-data/description/description.tsx
- src/core/empty-data/empty-data.figma.tsx
- src/core/select-native/select-native.figma.tsx
- src/core/split-button/action/action.figma.tsx
- src/core/split-button/action/action.tsx
- src/core/split-button/action/anchor-action.tsx
- src/core/split-button/split-button-menu.figma.tsx
- src/core/split-button/split-button-menu.tsx
- src/core/split-button/split-button.figma.tsx
- src/storybook/changelog.mdx
- Currently, our engineers have a relatively steep learning curve when implementing UI provided by Design using Elements components for the first time.
- They need to read the minimal documentation provided for the component in Elements' storybook, understand it, then apply it correctly based on the design their implementing.
- Figma's Code Connect is intended to reduce this learning curve by providing code snippets for React within Figma itself that devs can copy-paste into their product. This should bootstrap their usage of Elements and reduce some of the learning curve.
- Further, with Figma's MCP server available, its possible to have an AI agent retrieve this code snippet itself when asked to scaffold out the UI for a selection the engineer has made within the Figma desktop app.
- …
> feat: add code connect for `Divider`, `EmptyData`, `SelectNative`, and `SplitButton`

- figma.config.json
- src/core/folder-tabs/count-label/count-label.figma.tsx
- src/core/folder-tabs/count-label/count-label.tsx
- src/core/folder-tabs/folder-tabs.figma.tsx
- src/core/folder-tabs/tab/tab.figma.tsx
- src/core/folder-tabs/tab/tab.tsx
- src/core/primary-tabs/primary-tabs-item.figma.tsx
- src/core/primary-tabs/primary-tabs-item.tsx
- src/core/primary-tabs/primary-tabs.figma.tsx
- src/core/secondary-tabs/secondary-tabs-item.figma.tsx
- src/core/secondary-tabs/secondary-tabs-item.tsx
- src/core/secondary-tabs/secondary-tabs.figma.tsx
- src/core/tooltip/tooltip.figma.tsx
- src/storybook/changelog.mdx
- vite.config.ts
- Currently, our engineers have a relatively steep learning curve when implementing UI provided by Design using Elements components for the first time.
- They need to read the minimal documentation provided for the component in Elements' storybook, understand it, then apply it correctly based on the design their implementing.
- Figma's Code Connect is intended to reduce this learning curve by providing code snippets for React within Figma itself that devs can copy-paste into their product. This should bootstrap their usage of Elements and reduce some of the learning curve.
- Further, with Figma's MCP server available, its possible to have an AI agent retrieve this code snippet itself when asked to scaffold out the UI for a selection the engineer has made within the Figma desktop app.
- …
> feat: add code connect for `FolderTabs`, `PrimaryTabs`, `SecondaryTabs`, and `Tooltip`

- figma.config.json
- src/core/dialog/body/body.tsx
- src/core/dialog/dialog.figma.tsx
- src/core/dialog/footer/footer.tsx
- src/core/dialog/header/close-button.tsx
- src/core/dialog/header/header.tsx
- src/core/drawer/body/body.tsx
- src/core/drawer/drawer.figma.tsx
- src/core/drawer/footer/footer.tsx
- src/core/drawer/header/close-button.tsx
- src/core/drawer/header/header.tsx
- src/core/menu/group/group.figma.tsx
- src/core/menu/group/group.tsx
- src/core/menu/item/anchor-item.tsx
- src/core/menu/item/item.figma.tsx
- src/core/menu/item/item.tsx
- src/core/menu/menu.figma.tsx
- src/storybook/changelog.mdx
- Currently, our engineers have a relatively steep learning curve when implementing UI provided by Design using Elements components for the first time.
- They need to read the minimal documentation provided for the component in Elements' storybook, understand it, then apply it correctly based on the design their implementing.
- Figma's Code Connect is intended to reduce this learning curve by providing code snippets for React within Figma itself that devs can copy-paste into their product. This should bootstrap their usage of Elements and reduce some of the learning curve.
- Further, with Figma's MCP server available, its possible to have an AI agent retrieve this code snippet itself when asked to scaffold out the UI for a selection the engineer has made within the Figma desktop app.
- …
> feat: add code connect for `Dialog`, `Drawer`, and `Menu`

- figma.config.json
- src/core/table/body-cell/body-cell.figma.tsx
- src/core/table/body-cell/body-cell.tsx
- src/core/table/body-row/body-row.figma.tsx
- src/core/table/body-row/body-row.tsx
- src/core/table/body/body.tsx
- src/core/table/checkbox/checkbox.tsx
- src/core/table/double-line-layout/double-line-layout.tsx
- src/core/table/head/head.tsx
- src/core/table/header-cell/header-cell.figma.tsx
- src/core/table/header-cell/header-cell.tsx
- src/core/table/header-row/header-row.figma.tsx
- src/core/table/header-row/header-row.tsx
- src/core/table/more-actions/more-actions.tsx
- src/core/table/primary-action/primary-action-button.tsx
- src/core/table/primary-action/primary-action.figma.tsx
- src/core/table/primary-action/primary-action.tsx
- src/core/table/primary-data/primary-data.figma.tsx
- src/core/table/primary-data/primary-data.tsx
- src/core/table/sort-button/sort-button.tsx
- src/core/table/toolbar/toolbar.figma.tsx
- src/core/table/toolbar/toolbar.tsx
- src/storybook/changelog.mdx
- Currently, our engineers have a relatively steep learning curve when implementing UI provided by Design using Elements components for the first time.
- They need to read the minimal documentation provided for the component in Elements' storybook, understand it, then apply it correctly based on the design their implementing.
- Figma's Code Connect is intended to reduce this learning curve by providing code snippets for React within Figma itself that devs can copy-paste into their product. This should bootstrap their usage of Elements and reduce some of the learning curve.
- Further, with Figma's MCP server available, its possible to have an AI agent retrieve this code snippet itself when asked to scaffold out the UI for a selection the engineer has made within the Figma desktop app.
- …
> feat: add code connect for `Table`

- .github/workflows/test-pr.yml
- src/core/avatar/__tests__/__snapshots__/avatar.test.tsx.snap
- src/core/avatar/__tests__/avatar.test.tsx
- src/core/avatar/avatar.stories.tsx
- src/core/chip-select/chip/styles.ts
- src/core/input/checkbox/styles.ts
- src/core/split-button/action/__tests__/action-base.test.tsx
- src/core/split-button/menu-button/__tests__/menu-button.test.tsx
- src/core/split-button/menu-button/menu-button.stories.tsx
- src/core/status-indicator/status-indicator.stories.tsx
- src/core/supplementary-info/supplementary-info-item.stories.tsx
- src/core/supplementary-info/supplementary-info.stories.tsx
- src/core/table/checkbox/__tests__/checkbox.test.tsx
- src/core/table/more-actions/__tests__/more-actions.test.tsx
- src/lab/radio/styles.ts
CI has not been correctly report TS or lint errors during the `yarn check` stage. This will be looked at separately, but this PR resolves all type and lint errors.
> fix: type and lint errors

- .yarnrc.yml
- src/core/app-switcher/__tests__/app-switcher.test.tsx
- src/core/bottom-bar/item/__tests__/item-anchor.test.tsx
- src/core/bottom-bar/item/__tests__/item-button.test.tsx
- src/core/dialog/__story__/useDialogContextDecorator.tsx
- src/core/drawer/__story__/useDrawerBreakpointDecorator.tsx
- src/core/drawer/__story__/useDrawerContextDecorator.tsx
- src/core/folder-tabs/__story__/useFolderTabsContainerDecorator.tsx
- src/core/primary-tabs/__tests__/primary-tabs.test.tsx
- src/core/secondary-tabs/__tests__/secondary-tabs.test.tsx
- src/core/side-bar/__story__/use-side-bar-context-decorator.tsx
- src/core/side-bar/__story__/use-side-bar-width-decorator.tsx
- src/core/side-bar/__story__/use-viewport-height-decorator.tsx
- src/core/side-bar/__tests__/side-bar.test.tsx
- src/core/side-bar/collapse-button/__tests__/collapse-button.test.tsx
- src/core/side-bar/menu-group/__tests__/menu-group.test.tsx
- src/core/side-bar/menu-item/__tests__/menu-item.test.tsx
- src/core/side-bar/submenu-item/__tests__/submenu-item.test.tsx
- src/core/top-bar/avatar-button/__tests__/avatar-button.test.tsx
- src/core/top-bar/main-nav/__tests__/main-nav.test.tsx
- src/core/top-bar/nav-dropdown-button/__tests__/nav-dropdown-button.test.tsx
- src/core/top-bar/nav-icon-item/__tests__/nav-icon-item-button.test.tsx
- src/core/top-bar/nav-item/__tests__/nav-item.test.tsx
- src/core/top-bar/nav-search-button/__tests__/nav-search-button.test.tsx
- src/core/top-bar/nav-search-icon-item/__tests__/nav-search-icon-item.test.tsx
- src/lab/radio-group/__tests__/radio-group.test.tsx
- src/lab/radio/__tests__/radio.test.tsx
- src/lab/search-input/__tests__/search-input.test.tsx
Updates our Yarn install mode to `pnpm` rather than the current `node-modules`. This brings us some improvements: https://yarnpkg.com/features/linkers#nodelinker-pnpm
This change picked up ghost dependency imports (imports from `@storybook/react` which is not a direct dependency of the package). These have all been fixed.
> chore: use pnpm install mode with Yarn

- src/core/app-switcher/__tests__/config.test.ts
- src/core/app-switcher/app-switcher.stories.tsx
- src/core/app-switcher/config.ts
- src/storybook/changelog.mdx
Allows the MMI product to display in the AppSwitcher.
> feat: Allow MMI product to display in AppSwitcher
